Homework day8 collections 1-5 tasks
IrynaAlesiyuk/Iryna_Alesiyuk_AT_G8 pull request #8
Opened 2023-10-25 18:28 UTC by IrynaAlesiyuk

2023-10-26 20:55 UTC, ArtemVoo requested changes

2023-10-26 20:55 UTC, ArtemVoo commented on src/homework/day8/collectionTask/TaskTwo.java
> +        List<String> figures = Arrays.asList("Овал", "Круг", "Квадрат", "Эллипс");
Должно быть 5 фигур, "Прямоугольник" пропущен

2023-10-26 20:55 UTC, ArtemVoo commented on src/homework/day8/collectionTask/TaskTwo.java
> +                System.out.print(" - ");
После for-each надо отпечатать слова через "-" в файл, а не в консоль.

2023-10-26 20:55 UTC, ArtemVoo commented on src/homework/day8/collectionTask/TaskThree.java
> +        }
Мне кажется, что должно быть что-то типа -  Sum of all letters : 17. А у тебя получается считает количество букв в каждом городе по отдельности.

2023-10-26 20:55 UTC, ArtemVoo commented on src/homework/day8/collectionTask/TaskFour.java
> +        }
После for-each надо отпечатать слова в файл cars с новой строки в кавычках, а не в консоль.

2023-10-26 20:55 UTC, ArtemVoo commented on src/homework/day8/collectionTask/TaskFive.java
> +        int counter = 0;
А здесь точно нужно: "int counter = 0;" ?

2023-10-27 08:07 UTC, IrynaAlesiyuk commented on src/homework/day8/collectionTask/TaskTwo.java
> +        List<String> figures = Arrays.asList("Овал", "Круг", "Квадрат", "Эллипс");
fix

2023-10-27 08:32 UTC, IrynaAlesiyuk commented on src/homework/day8/collectionTask/TaskTwo.java
> +                System.out.print(" - ");
fix

2023-10-27 09:00 UTC, IrynaAlesiyuk commented on src/homework/day8/collectionTask/TaskFour.java
> +        }
fix

2023-10-27 09:04 UTC, IrynaAlesiyuk commented on src/homework/day8/collectionTask/TaskThree.java
> +        }
fix

2023-10-27 09:29 UTC, ArtemVoo approved these changes
All is  ok

2023-10-27 09:31 UTC, merged