task6 - task15
IrynaAlesiyuk/Iryna_Alesiyuk_AT_G8 pull request #9
Opened 2023-10-27 17:45 UTC by IrynaAlesiyuk

2023-10-27 20:25 UTC, ArtemVoo approved these changes
All is ok

2023-10-30 09:17 UTC, ArtemVoo requested changes

2023-10-30 09:17 UTC, ArtemVoo commented on src/homework/day8/collectionTask/TaskEleven.java
> +            System.out.println(bubbles);
Здесь необходимо использовать (.toString())

2023-10-30 09:17 UTC, ArtemVoo commented on src/homework/day8/collectionTask/TaskTwelwe.java
> +            System.out.println(people);
Здесь необходимо использовать (.toString())

2023-10-30 09:31 UTC, IrynaAlesiyuk commented on src/homework/day8/collectionTask/TaskTwelwe.java
> +            System.out.println(people);
![image](https://github.com/IrynaAlesiyuk/Iryna_Alesiyuk_AT_G8/assets/63403016/6c26e5c3-f560-476e-a5a1-6a31d66e49ed)

2023-10-30 10:42 UTC, ArtemVoo commented on src/homework/day8/collectionTask/TaskTwelwe.java
> +            System.out.println(people);
Я думал что-то такое увидеть - System.out.println(people.get(i).toString());

2023-10-30 11:52 UTC, IrynaAlesiyuk commented on src/homework/day8/collectionTask/TaskEleven.java
> +            System.out.println(bubbles);
fix

2023-10-30 11:53 UTC, IrynaAlesiyuk commented on src/homework/day8/collectionTask/TaskTwelwe.java
> +            System.out.println(people);
fix

2023-10-30 11:59 UTC, ArtemVoo approved these changes
All is ok

2023-10-30 12:28 UTC, merged